version: '3.7'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
