version: '3.7'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OPENAI_KEY=${OPENAI_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
