version: '3.7'

services:
  backend:
    build:
      context: ./recipes-suggester
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
